# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDpN1KuzuICM93mko_tBnp_MeyJ-ctpT
"""

import streamlit as st
import pandas as pd
from streamlit_gsheets import GSheetsConnection
import easyocr
import numpy as np
import cv2

# Configuración de página
st.set_page_config(page_title="Panini 2026 Cloud", layout="wide", page_icon="⚽")

# --- CONEXIÓN A BASE DE DATOS ---
# Esto permite que los datos se guarden en tu Google Sheet
conn = st.connection("gsheets", type=GSheetsConnection)

# --- LOGIN / INICIO DE SESIÓN ---
if 'usuario' not in st.session_state:
    st.title("🔑 Álbum Panini 2026 - Inicio de Sesión")
    st.info("Ingresa tu nombre para cargar tu colección personal.")
    user_input = st.text_input("Usuario (Ej: Tono):").strip().replace(" ", "_")

    if st.button("Entrar a mi Álbum"):
        if user_input:
            st.session_state.usuario = user_input
            st.rerun()
        else:
            st.warning("Por favor, ingresa un nombre.")
    st.stop()

# --- CARGA DE DATOS ---
@st.cache_resource
def load_ocr():
    return easyocr.Reader(['en'])

reader = load_ocr()

# Intentamos cargar los datos del usuario desde Google Sheets
# Si es usuario nuevo, cargamos el CSV base
@st.cache_data(ttl=10) # Se actualiza cada 10 segundos
def get_data():
    try:
        # Intenta leer la pestaña con el nombre del usuario
        return conn.read(worksheet=st.session_state.usuario)
    except:
        # Si no existe la pestaña, carga el CSV original por primera vez
        df_base = pd.read_csv("album_panini_2026_completo_980.csv")
        df_base['Obtenido'] = False
        df_base['Cantidad'] = 0
        return df_base

if 'df' not in st.session_state:
    st.session_state.df = get_data()

# --- FUNCIONES DE GUARDADO ---
def guardar_progreso():
    try:
        # Forzamos la actualización de la hoja específica
        conn.update(
            worksheet=st.session_state.usuario,
            data=st.session_state.df
        )
        st.toast("☁️ ¡Progreso guardado en la nube!")
    except Exception as e:
        st.error(f"Hubo un detalle al guardar: {e}")
        st.info("Revisa que el nombre de la pestaña en Google Sheets sea EXACTAMENTE igual al que usaste al entrar.")

# --- INTERFAZ PRINCIPAL ---
st.title(f"⚽ Álbum de {st.session_state.usuario.replace('_', ' ')}")

col1, col2 = st.columns([1, 1])

with col1:
    st.header("📸 Escanear")
    foto = st.camera_input("Enfoca el número")
    if foto:
        file_bytes = np.asarray(bytearray(foto.read()), dtype=np.uint8)
        img = cv2.imdecode(file_bytes, 1)
        with st.spinner("Procesando..."):
            resultado = reader.readtext(img)
            texto_ia = " ".join([res[1].upper() for res in resultado])
            encontrado = None
            for id_cromo in st.session_state.df['ID_Cromo']:
                if id_cromo.replace("_", "") in texto_ia.replace(" ", ""):
                    encontrado = id_cromo
                    break
            if encontrado:
                st.success(f"Detectado: {encontrado}")
                if st.button(f"Confirmar {encontrado}"):
                    idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == encontrado]
                    st.session_state.df.at[idx[0], 'Obtenido'] = True
                    st.session_state.df.at[idx[0], 'Cantidad'] += 1
                    guardar_progreso()
                    st.rerun()

with col2:
    st.header("✍️ Manual")
    id_manual = st.text_input("Ingresa ID:").upper()
    if st.button("Registrar"):
        idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == id_manual]
        if not idx.empty:
            st.session_state.df.at[idx[0], 'Obtenido'] = True
            st.session_state.df.at[idx[0], 'Cantidad'] += 1
            guardar_progreso()
            st.success("¡Guardado!")
            st.rerun()

# --- VISUALIZADOR ---
st.divider()
sel = st.selectbox("Equipo:", st.session_state.df['Seleccion'].unique())
df_sel = st.session_state.df[st.session_state.df['Seleccion'] == sel]
cols = st.columns(5)
for i, (index, row) in enumerate(df_sel.iterrows()):
    with cols[i % 5]:
        if row['Obtenido']:
            st.success(f"✅ {row['ID_Cromo']}")
            if row['Cantidad'] > 1: st.caption(f"Repes: {int(row['Cantidad']-1)}")
        else:
            st.error(f"❌ {row['ID_Cromo']}")