# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDpN1KuzuICM93mko_tBnp_MeyJ-ctpT
"""

import streamlit as st
import pandas as pd
import easyocr
import numpy as np
import cv2

# Configuración de la página
st.set_page_config(page_title="Gestor Panini 2026", layout="wide", page_icon="⚽")

# 1. Cargar el lector de IA (OCR) una sola vez para que no sea lento
@st.cache_resource
def load_ocr():
    return easyocr.Reader(['en'])

reader = load_ocr()

# 2. Cargar el dataset
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("album_panini_2026_completo_980.csv")
        if 'Obtenido' not in df.columns:
            df['Obtenido'] = False
            df['Cantidad'] = 0
        return df
    except FileNotFoundError:
        st.error("⚠️ No se encontró el archivo CSV.")
        return pd.DataFrame()

if 'df' not in st.session_state:
    st.session_state.df = load_data()

st.title("⚽ Mi Álbum Panini 2026")

# --- BARRA LATERAL (PROGRESO E INTERCAMBIO) ---
st.sidebar.header("📊 Estadísticas")
conseguidas = st.session_state.df[st.session_state.df['Obtenido']].shape[0]
st.sidebar.metric("Progreso", f"{conseguidas}/980")

st.sidebar.divider()
st.sidebar.header("🔄 Intercambio")
df_rep = st.session_state.df[st.session_state.df['Cantidad'] > 1]
if not df_rep.empty:
    cromo_dar = st.sidebar.selectbox("Entregar repetida:", options=df_rep['ID_Cromo'].tolist())
    if st.sidebar.button("Confirmar Entrega"):
        idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == cromo_dar]
        st.session_state.df.at[idx[0], 'Cantidad'] -= 1
        st.rerun()

# --- SECCIÓN PRINCIPAL: REGISTRO ---
col1, col2 = st.columns([1, 1])

with col1:
    st.header("📸 Escanear Estampa")
    foto = st.camera_input("Enfoca el ID (ej: MEX 10)")

    if foto:
        file_bytes = np.asarray(bytearray(foto.read()), dtype=np.uint8)
        img = cv2.imdecode(file_bytes, 1)

        with st.spinner("Leyendo número..."):
            resultado = reader.readtext(img)
            texto_ia = " ".join([res[1].upper() for res in resultado])
            st.write(f"Detectado: `{texto_ia}`")

            # Buscar coincidencia en el dataset
            encontrado = None
            for id_cromo in st.session_state.df['ID_Cromo']:
                limpio = id_cromo.replace("_", "")
                if limpio in texto_ia.replace(" ", ""):
                    encontrado = id_cromo
                    break

            if encontrado:
                st.success(f"¡ID Reconocido: {encontrado}!")
                if st.button(f"Validar y Guardar {encontrado}"):
                    idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == encontrado]
                    st.session_state.df.at[idx[0], 'Obtenido'] = True
                    st.session_state.df.at[idx[0], 'Cantidad'] += 1
                    st.rerun()

with col2:
    st.header("✍️ Registro Manual")
    id_manual = st.text_input("Ingresa ID manualmente:").upper()
    if st.button("Registrar"):
        idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == id_manual]
        if not idx.empty:
            st.session_state.df.at[idx[0], 'Obtenido'] = True
            st.session_state.df.at[idx[0], 'Cantidad'] += 1
            st.success("¡Registrado!")
            st.rerun()

# --- VISUALIZACIÓN ---
st.divider()
seleccion = st.selectbox("Selección:", st.session_state.df['Seleccion'].unique())
df_sel = st.session_state.df[st.session_state.df['Seleccion'] == seleccion]
cols = st.columns(5)
for i, (index, row) in enumerate(df_sel.iterrows()):
    with cols[i % 5]:
        if row['Obtenido']:
            st.success(f"✅ {row['ID_Cromo']}")
            if row['Cantidad'] > 1: st.caption(f"Repes: {int(row['Cantidad']-1)}")
        else:
            st.error(f"❌ {row['ID_Cromo']}")