# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CDpN1KuzuICM93mko_tBnp_MeyJ-ctpT
"""

import streamlit as st
import pandas as pd

# Configuración de la página
st.set_page_config(page_title="Gestor Álbum Panini 2026", layout="wide", page_icon="⚽")

# 1. Cargar el dataset (Asegúrate de tener el archivo CSV en la misma carpeta)
@st.cache_data
def load_data():
    try:
        df = pd.read_csv("album_panini_2026_completo_980.csv")
        if 'Obtenido' not in df.columns:
            df['Obtenido'] = False
            df['Cantidad'] = 0
        return df
    except FileNotFoundError:
        st.error("⚠️ No se encontró el archivo 'album_panini_2026_completo_980.csv'.")
        return pd.DataFrame()

# Inicializar el estado de la sesión
if 'df' not in st.session_state:
    st.session_state.df = load_data()

st.title("⚽ Mi Álbum Panini 2026")

# --- BARRA LATERAL: PROGRESO Y REPETIDAS ---
st.sidebar.header("📊 Estadísticas")
total_estampas = len(st.session_state.df)
conseguidas = st.session_state.df[st.session_state.df['Obtenido']].shape[0]
porcentaje = (conseguidas / total_estampas) * 100

st.sidebar.metric("Progreso Total", f"{conseguidas}/{total_estampas}", f"{porcentaje:.1f}%")

st.sidebar.divider()
st.sidebar.header("🔄 Centro de Intercambio")
df_repetidas = st.session_state.df[st.session_state.df['Cantidad'] > 1]

if not df_repetidas.empty:
    st.sidebar.write(f"Tienes **{int(df_repetidas['Cantidad'].sum() - len(df_repetidas))}** repetidas.")
    cromo_dar = st.sidebar.selectbox("¿Cuál vas a entregar?", options=df_repetidas['ID_Cromo'].tolist())

    if st.sidebar.button("Confirmar Entrega"):
        idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == cromo_dar]
        st.session_state.df.at[idx[0], 'Cantidad'] -= 1
        st.sidebar.success(f"Entregaste {cromo_dar}")
        st.rerun()

    if st.sidebar.button("Lista para WhatsApp"):
        msg = "🏆 *Mis repetidas Panini 2026:* \n"
        for _, r in df_repetidas.iterrows():
            msg += f"• {r['ID_Cromo']} - x{int(r['Cantidad']-1)}\n"
        st.sidebar.code(msg)
else:
    st.sidebar.info("Aún no tienes repetidas.")

# --- SECCIÓN PRINCIPAL: REGISTRO ---
col1, col2 = st.columns([1, 1])

with col1:
    st.header("📸 Registro Rápido")
    # Nota: st.camera_input funciona nativo en celular
    foto = st.camera_input("Toma foto al cromo")
    if foto:
        st.info("💡 En la versión Pro, aquí se activará el OCR para leer el número.")

with col2:
    st.header("✍️ Registro Manual")
    id_input = st.text_input("ID del cromo (ej. MEX_01, ARG_10)").upper()
    if st.button("Registrar Estampa"):
        idx = st.session_state.df.index[st.session_state.df['ID_Cromo'] == id_input]
        if not idx.empty:
            st.session_state.df.at[idx[0], 'Obtenido'] = True
            st.session_state.df.at[idx[0], 'Cantidad'] += 1
            st.success(f"¡{id_input} registrado!")
            st.rerun()
        else:
            st.error("ID no válido.")

# --- VISOR POR SELECCIÓN ---
st.divider()
seleccion = st.selectbox("Ver Selección:", st.session_state.df['Seleccion'].unique())
df_sel = st.session_state.df[st.session_state.df['Seleccion'] == seleccion]

cols = st.columns(5)
for i, (index, row) in enumerate(df_sel.iterrows()):
    with cols[i % 5]:
        if row['Obtenido']:
            st.success(f"✅ **{row['ID_Cromo']}**\n\n{row['Nombre_Jugador']}")
            if row['Cantidad'] > 1:
                st.caption(f"Tienes {int(row['Cantidad']-1)} repetida(s)")
        else:
            st.error(f"❌ **{row['ID_Cromo']}**\n\n{row['Nombre_Jugador']}")